  
name: Tests and code coverage

on:
  push:
    branches:
    - feature/*
    - ci

jobs:
 build:

    name: Build and Test
    runs-on: macos-latest
    timeout-minutes: 60
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
      working-directory: ./builder
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: install fastlane
        run: |
          brew install fastlane
      - name: macOS (5.1)
        run: fastlane scan --scheme "TealiumCoreTests-iOS"
        working-directory: ${{env.working-directory}}
      - name: archive code coerage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: test_output/report.html